### ISSUE TITLE
Structure Spawner does not have a shape component

### ISSUE THREAD

**Issue by nihal111** [Terasology/StructureTemplates#17]
Throwing away a structure spawner (using `Q`) gives a Physics error.
```
java.lang.IllegalArgumentException: Creating physics object that requires a ShapeComponent or CharacterMovementComponent, but has neither. Entity: EntityRef{id = 14403, netId = 0, prefab = 'AdventureAssets:bladeRoom'}
	at org.terasology.physics.bullet.BulletPhysics.getShapeFor(BulletPhysics.java:676)
	at org.terasology.physics.bullet.BulletPhysics.newRigidBody(BulletPhysics.java:508)
	at org.terasology.physics.bullet.BulletPhysics.getRigidBody(BulletPhysics.java:345)
	at org.terasology.physics.engine.PhysicsSystem.onImpulse(PhysicsSystem.java:107)
	at org.terasology.physics.engine.PhysicsSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.inventory.CharacterInventorySystem.onDropItemRequest(CharacterInventorySystem.java:134)
	at org.terasology.logic.inventory.CharacterInventorySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.inventory.CharacterInventorySystem.onDropItemRequest(CharacterInventorySystem.java:201)
	at org.terasology.logic.inventory.CharacterInventorySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:192)
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:472)
	at org.terasology.input.InputSystem.update(InputSystem.java:280)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:188)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:441)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:397)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:373)
	at org.terasology.engine.Terasology.main(Terasology.java:153)
15:50:58.393 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
15:50:58.394 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
15:50:59.419 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
15:51:20.390 [main] WARN  o.t.physics.bullet.BulletPhysics - Deleting non existing rigidBody from physics engine?! Entity: EntityRef{id = 14403, netId = 0, prefab = 'AdventureAssets:bladeRoom'}
```

**Comment by flo** [comment]
That is certainly a new bug as I remember dropping spawners even in multipayer

**Comment by flo** [comment]
How did you obtain the item?

**Comment by nihal111** [comment]
Realised that my structure prefab did not have:
```
/* For debugging purposes it is an item: */
  "parent" : "engine:iconItem",
  "DisplayName" : {
    "name" : "A room with swinging blades"
  },
  "Item" : {
    "icon" : "engine:items#whiteRecipe"
  },
  "SpawnStructureAction": {}
```
This is not generated when you do the "Selected -> Clipboard" option on the Structure Template Origin block.
